project_id = "msbhhsrtfqfqcsofnsuy"

[functions.invite-user]
verify_jwt = false

[functions.manage-user]
verify_jwt = false

[functions.list-users]
verify_jwt = false

[functions.deactivate-expired-notice]
verify_jwt = false
